version: "3"

services:
  myMysqlNode:
    image: zfq17876911936/chaojigongshi-mysql:fdg-1.0
    container_name: myMysqlNode
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - ethnet
    restart: on-failure

  myRedisNode:
    image: redis
    container_name: myRedisNode
    ports:
      - "6379:6379"
    networks:
      - ethnet
    restart: on-failure

  myNode:
    image: zfq17876911936/chaojigongshi-node:fdg-1.0-refactor
    container_name: myNode
    volumes:
      - ./nodeConf:/conf
    depends_on:
      - myMysqlNode
    networks:
      - ethnet
    restart: on-failure

  myEthNode:
    # 生产环境使用
    image: zfq17876911936/chaojigongshi-ethereum-client-go:fdg-1.0-refactor-918
    # 测试环境使用
    #image: zfq17876911936/chaojigongshi-ethereum-client-go:fdg-1.0-ubuntu
    container_name: myEthNode
    volumes:
      - ./genesis:/genesis
      # 生产环境使用
      - ./data:/data
      - ./command:/usr/local/bin
    ports:
      - "30301:30303/tcp"
      - "30301:30303/udp"
      - "18545:8545"
      - "18546:8546"
    networks:
      - ethnet
    restart: on-failure

networks:
  ethnet:
